---
title: "Fig1"
author: "N Toyohara"
output: html_document
---

[← Index（目次）に戻る](https://toyohara-norihiko.github.io/Ronkyu2025/)

---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r step1, echo=FALSE}
library(openxlsx)
library(WaveletComp)
library(gifski)

## ---- データ読み込み ----
filnam <- "kansai_cli_ci_c.xlsx"
data   <- read.xlsx(filnam, sheet = 1)

## ---- 日付の作成（2018年1月～　月次）
date1 <- seq.Date(from = as.Date("2018-01-01"),
                  by   = "month",
                  length.out = nrow(data))

## ---- データフレームの作成
df1 <- cbind.data.frame(date = date1, data)
```

```{r step2, echo=FALSE}
## ---- kansai_cliの作成
kansai_cli<-0.473*data$osaka_cli+0.235*data$hyogo_cli+0.127*data$kyoto_cli+0.074*data$shiga_cli+0.045*data$nara_cli+0.046*data$waka_cli

## ---- データフレームに追加
df1 <- cbind.data.frame(date = date1, data,kansai_cli=kansai_cli)

# ---- kansai_cliを基準化
x <- as.numeric(kansai_cli)
x <- (x - mean(x, na.rm = TRUE))/sd(x)

# ---- 時間インデックス ----
N <- length(x)     #期間の長さ
t <- seq_len(N)    #1,2,...,N を作成

## ---- Morlet型ウェーブレット母関数を定義 ----
morlet <- function(t, scale = 12, omega0 = 6) {
  tt <- t / scale
  pi^(-1/4) * exp(1i * omega0 * tt) * exp(-tt^2 / 2)
}
```

```{r fig1}
## グラフを作成し、jpgファイルに保存する関数　引数はaとb

fig1<-function(a=6,b=25){
    fignam=paste("fig1-",round(a/8,0),"_","a=",substr(paste("0",a,sep=""),nchar(paste("0",a,sep=""))-1,nchar(paste("0",a,sep=""))),"_","b=",b,".jpg",sep="")

    jpeg(fignam, width = 800, height = 600) 
      tau <- t - b
      psi <- morlet(tau, scale = a)   # 複素数列
      z   <- x * psi                  # 変換結果（複素数）
      Rez<-(Re(z)-mean(Re(z)))/sd(Re(z))
      Reps<-Re(psi)/sd(Re(psi))
    ymin <- min(x, Rez, Reps, na.rm = TRUE)
    ymax <- max(x, Rez, Reps, na.rm = TRUE)
    b_date<-format(date1[b], "%Y-%m")
    ## (1) 時間軸（年月）上での変換前後の比較
    plot(date1, x, type = "l", col = "red",
         ylim = c(ymin,ymax),
         xlab = "Date", ylab = "Value",
         main = paste0("Kansai_cli;Time domain (a = ", a, ", b = ", b_date, ")"))
    lines(date1, Reps, col = "gray10",lwd = 2)
    lines(date1, Rez,  col = "blue")
    abline(h = 0, col = "black", lwd = 1)
rect(
  xleft  = date1[max(1, b - 1.5*a)],
  xright = date1[min(N, b + 1.5*a)],
  ybottom = -5, ytop = 5,
  col = rgb(0.5, 0.5, 0.5, alpha = 0.15),
  border = NA
)
abline(v = date1[b], col = "gray30", lwd = 1.5, lty = 3)
    if (b >= 1 && b <= N) {
      abline(v = date1[b], col = "gray70", lty = 3)
    }
    legend("topleft",
           legend = c("x(t)", "Re(ψ)", "x(t)·Re(ψ)"),
           col    = c("red", "gray50", "blue"),
           lty    = 1,
           bty    = "n")
    dev.off()
    }

fig1(a=6,b=25)
fig1(a=12,b=25)
fig1(a=24,b=25)

```


