---
title: "Fig 3"
author: "N Toyohara"
output: html_document
---
[← Index（目次）に戻る](https://toyohara-norihiko.github.io/Ronkyu2025/)
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r step1, echo=FALSE}
library(openxlsx)
library(WaveletComp)

## ---- データ読み込み ----
filnam <- "kansai_cli_ci_c.xlsx"
data   <- read.xlsx(filnam, sheet = 1)

## ---- 日付の作成（2018年1月～　月次）
date1 <- seq.Date(from = as.Date("2018-01-01"),
                  by   = "month",
                  length.out = nrow(data))

## ---- データフレームの作成
df1 <- cbind.data.frame(date = date1, data)
```

```{r step2, echo=FALSE}
## ---- kansai_cliの作成
kansai_cli<-0.473*data$osaka_cli+0.235*data$hyogo_cli+0.127*data$kyoto_cli+0.074*data$shiga_cli+0.045*data$nara_cli+0.046*data$waka_cli

## ---- データフレームに追加
df1 <- cbind.data.frame(date = date1, data, kansai_cli=kansai_cli)

```

```{r step02, echo=FALSE}
# 月次データ前提（2018-01スタート）
dt <- 1            # 単位は「月」
dj <- 1/12         # 周波数分解能
lowerPeriod <- 2   # 最短周期（2ヶ月）
upperPeriod <- 64  # 最長周期（64ヶ月）

# 解析対象列（date 以外）

vars <- c("kansai_cli","osaka_cli","hyogo_cli","kyoto_cli","shiga_cli","nara_cli","waka_cli")

# 各系列について wavelet 解析

sink("nul")
results <- lapply(vars, function(v) {
analyze.wavelet(
my.data     = df1,
my.series   = v,
loess.span  = 0,           # トレンド除去なし
dt          = dt,
dj          = dj,
lowerPeriod = lowerPeriod,
upperPeriod = upperPeriod,
make.pval   = TRUE,
n.sim       = 100
)
})
sink()

```

```{r step03, echo=FALSE}
names(results) <- vars

# x軸の tick 位置とラベル（2018-01, 2018-02, ... を "%Y-%m" 表示）

time_ticks  <- 1:nrow(df1)                      # 1, 2, 3, ...
time_labels <- format(df1$date, "%Y-%m")        # "2018-01", "2018-02", ...

# 各系列のパワースペクトルを描画

for (v in vars) {
wt <- results[[v]]

wt.image(
wt,
main          = paste(v, "Wavelet Power Spectrum (Morlet)"),
legend.params = list(lab = "Power"),
# x軸まわり
spec.time.axis = list(
at     = time_ticks,
labels = time_labels,
las    = 2   # 縦書き風（ラベルを寝かせる→ 1, 2 など必要に応じて変更）
),
# y軸まわり
periodlab     = "Period (months)",
# そのほか
plot.coi      = TRUE,
plot.contour  = TRUE,
n.levels      = 100
)
}

```

